ksau: Add checks for upload() arguments * Gives broken download links with "index//file" instead of "index/file" since folder variable is empty when upload folder is not specified
Change-Id: Ib2ea4aff5ba7ace4e0485f090bc0d85c7a48f6b8

diff --git a/ksau b/ksau
--- a/ksau
+++ b/ksau
@@ -449,6 +449,14 @@ select_remote_most_free_cached
 if [[ $1 == "upload" ]]; then
     readonly file="$2"
     readonly u_folder="$3"
+    if [ -z "$file" ]; then
+        echo -e "Error: 'file path' is not specified. Upload aborted.\nSpecify which file to upload"
+        exit 1
+    fi
+    if [ -z "$u_folder" ]; then
+        echo -e "Error: 'upload directory' is not specified. Upload aborted.\nSpecify a folder name (can be anything) in which files will be uploaded to help organize files better"
+        exit 1
+    fi
     if [ -n "$KSAUOPT_SPECIFIC_REMOTE" ]; then
         SELECTED_REMOTE=$KSAUOPT_SPECIFIC_REMOTE
         upline 1; clearline
